name: FMC-Plugin
version: ${projectName}
description: ${projectDescription}
main: ${projectGroup}.spigot.Main
author: Bella
website: ${projectHP}
api-version: ${projectAPIVersion}
description: ${projectDescription}
depend:
  - LuckPerms
commands:
  fmc:
    usage: /<command>
    description: You can use FMC Spigot server command!
    executor: spigot_command.FMCCommand
  q:
    usage: /<command>
    description: You can confirm image map code generated at discord
    executor: spigot_command.Q
  tpr:
    usage: /<command>
    description: You can teleport to other player
    executor: spigot_command.TeleportRequest
  tprm:
    usage: /<command>
    description: You can teleport to other player
    executor: spigot_command.TeleportRequest
  tpra:
    usage: /<command>
    description: You can accept teleport request
    executor: spigot_command.TeleportAccept
  tprma:
    usage: /<command>
    description: You can accept teleport request
    executor: spigot_command.TeleportAccept
