name: Kishax
version: ${projectName}
description: ${projectDescription}
main: ${projectGroup}.spigot.Main
author: Takaya Maekawa
website: ${projectHP}
api-version: ${projectAPIVersion}
description: ${projectDescription}
depend:
  - LuckPerms
commands:
  kishax:
    usage: /<command>
    description: You can use Kishax Spigot server command!
    executor: net.kishax.mc.spigot.cmd.main.Command
  q:
    usage: /<command>
    description: You can confirm image map code generated at discord
    executor: net.kishax.mc.spigot.cmd.sub.Q
  tpr:
    usage: /<command>
    description: You can teleport to other player
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportRequest
  tprm:
    usage: /<command>
    description: You can teleport to other player
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportRequest
  tpra:
    usage: /<command>
    description: You can accept teleport request
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportAccept
  tprma:
    usage: /<command>
    description: You can accept teleport request
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportAccept
  tprd:
    usage: /<command>
    description: You can accept teleport request
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportAccept
  tprmd:
    usage: /<command>
    description: You can accept teleport request
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportAccept
  back:
    usage: /<command>
    description: You can teleport to back
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportBack
  registerpoint:
    usage: /<command>
    description: You can register point
    executor: net.kishax.mc.spigot.cmd.sub.teleport.RegisterTeleportPoint
  registerimagemap:
    usage: /<command>
    description: You can register image map
    executor: net.kishax.mc.spigot.cmd.sub.imagemap.RegisterImageMap
  nv:
    usage: /<command>
    description: You can open navi menu
    executor: net.kishax.mc.spigot.cmd.sub.teleport.Navi
permissions:
  kishax.*:
    description: Gives access to all kishax commands
    default: op
    children:
      kishax.reload: true
      kishax.fv: true
      kishax.mcvc: true
      kishax.portal: true
      kishax.portal.*: true
      kishax.hideplayer: true
      kishax.im: true
      kishax.image: true
      kishax.image.*: true
      kishax.menu: true
      kishax.button: true
      kishax.check: true
      kishax.setpoint: true
      kishax.confirm: true
      kishax.back: true
      kishax.test: true
  kishax.confirm:
    description: Allows use of /kishax confirm
    default: true
  kishax.check:
    description: Allows use of /kishax check
    default: true
  kishax.portal:
    description: Allows use of /kishax portal
    default: op
  kishax.portal.*:
    description: Gives access to all portal commands
    default: op
    children:
      kishax.portal.wand: true
      kishax.portal.delete: true
      kishax.portal.rename: true
      kishax.portal.nether: true
  kishax.image:
    description: Allows use of /kishax image
    default: op
  kishax.image.*:
    description: Gives access to all image commands
    default: op
    children:
      kishax.image.create: true
      kishax.image.q: true
