name: FMC-Plugin
version: ${projectName}
description: ${projectDescription}
main: ${projectGroup}.spigot.Main
author: Bella
website: ${projectHP}
api-version: ${projectAPIVersion}
description: ${projectDescription}
depend:
  - LuckPerms
commands:
  fmc:
    usage: /<command>
    description: You can use FMC Spigot server command!
    executor: keyp.forev.fmc.spigot.cmd.main.FMCCommand
  q:
    usage: /<command>
    description: You can confirm image map code generated at discord
    executor: keyp.forev.fmc.spigot.cmd.sub.Q
  tpr:
    usage: /<command>
    description: You can teleport to other player
    executor: keyp.forev.fmc.spigot.cmd.sub.teleport.TeleportRequest
  tprm:
    usage: /<command>
    description: You can teleport to other player
    executor: keyp.forev.fmc.spigot.cmd.sub.teleport.TeleportRequest
  tpra:
    usage: /<command>
    description: You can accept teleport request
    executor: keyp.forev.fmc.spigot.cmd.sub.teleport.TeleportAccept
  tprma:
    usage: /<command>
    description: You can accept teleport request
    executor: keyp.forev.fmc.spigot.cmd.sub.teleport.TeleportAccept
  back:
    usage: /<command>
    description: You can teleport to back
    executor: keyp.forev.fmc.spigot.cmd.sub.teleport.TeleportBack
  registerpoint:
    usage: /<command>
    description: You can register point
    executor: keyp.forev.fmc.spigot.cmd.sub.teleport.RegisterTeleportPoint
  nv:
    usage: /<command>
    description: You can open navi menu
    executor: keyp.forev.fmc.spigot.cmd.sub.teleport.Navi