name: Kishax
version: ${projectName}
description: ${projectDescription}
main: ${projectGroup}.spigot.Main
author: verazza
website: ${projectHP}
api-version: ${projectAPIVersion}
description: ${projectDescription}
depend:
  - LuckPerms
commands:
  kishax:
    usage: /<command>
    description: You can use Kishax Spigot server command!
    executor: net.kishax.mc.spigot.cmd.main.Command
  q:
    usage: /<command>
    description: You can confirm image map code generated at discord
    executor: net.kishax.mc.spigot.cmd.sub.Q
  tpr:
    usage: /<command>
    description: You can teleport to other player
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportRequest
  tprm:
    usage: /<command>
    description: You can teleport to other player
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportRequest
  tpra:
    usage: /<command>
    description: You can accept teleport request
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportAccept
  tprma:
    usage: /<command>
    description: You can accept teleport request
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportAccept
  tprd:
    usage: /<command>
    description: You can accept teleport request
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportAccept
  tprmd:
    usage: /<command>
    description: You can accept teleport request
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportAccept
  back:
    usage: /<command>
    description: You can teleport to back
    executor: net.kishax.mc.spigot.cmd.sub.teleport.TeleportBack
  registerpoint:
    usage: /<command>
    description: You can register point
    executor: net.kishax.mc.spigot.cmd.sub.teleport.RegisterTeleportPoint
  registerimagemap:
    usage: /<command>
    description: You can register image map
    executor: net.kishax.mc.spigot.cmd.sub.imagemap.RegisterImageMap
  nv:
    usage: /<command>
    description: You can open navi menu
    executor: net.kishax.mc.spigot.cmd.sub.teleport.Navi
