services:
  kishax-server:
    build: .
    container_name: kishax-minecraft
    restart: unless-stopped
    environment:
      # MySQL Configuration (RDS MySQL)
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mc}
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      
      # Spigot/Velocity Configuration
      SPIGOT_MEMORY: ${SPIGOT_MEMORY:-6G}
      VELOCITY_MEMORY: ${VELOCITY_MEMORY:-1G}
      CONFIRM_URL: ${CONFIRM_URL:-http://10.0.36.61:8080/mc/auth}
      HOME_SERVER_NAME: ${HOME_SERVER_NAME:-spigot}
      HOME_SERVER_IP: ${HOME_SERVER_IP:-127.0.0.1}
      
      # AWS Configuration
      AWS_REGION: ${AWS_REGION:-ap-northeast-1}
      MC_WEB_SQS_ACCESS_KEY_ID: ${MC_WEB_SQS_ACCESS_KEY_ID}
      MC_WEB_SQS_SECRET_ACCESS_KEY: ${MC_WEB_SQS_SECRET_ACCESS_KEY}
      TO_WEB_QUEUE_URL: ${TO_WEB_QUEUE_URL}
      TO_MC_QUEUE_URL: ${TO_MC_QUEUE_URL}
      TO_DISCORD_QUEUE_URL: ${TO_DISCORD_QUEUE_URL}
      
      # Redis Configuration (i-b host Redis #1)
      REDIS_URL: ${REDIS_URL:-redis://10.0.36.61:6379}
      REDIS_CONNECTION_TIMEOUT: ${REDIS_CONNECTION_TIMEOUT:-5000}
      REDIS_COMMAND_TIMEOUT: ${REDIS_COMMAND_TIMEOUT:-3000}
      
      # Queue Configuration
      QUEUE_MODE: ${QUEUE_MODE:-MC}
      SQS_WORKER_ENABLED: ${SQS_WORKER_ENABLED:-true}
      SQS_WORKER_POLLING_INTERVAL_SECONDS: ${SQS_WORKER_POLLING_INTERVAL_SECONDS:-5}
      SQS_WORKER_MAX_MESSAGES: ${SQS_WORKER_MAX_MESSAGES:-10}
      SQS_WORKER_WAIT_TIME_SECONDS: ${SQS_WORKER_WAIT_TIME_SECONDS:-20}
      SQS_WORKER_VISIBILITY_TIMEOUT_SECONDS: ${SQS_WORKER_VISIBILITY_TIMEOUT_SECONDS:-30}
      
      # Auth API Configuration
      AUTH_API_URL: ${AUTH_API_URL:-http://10.0.36.61:8080}
      AUTH_API_KEY: ${AUTH_API_KEY}
      
      # Logging Configuration
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    
    volumes:
      - minecraft_data:/mc/spigot/world
      - minecraft_data_nether:/mc/spigot/world_nether
      - minecraft_data_the_end:/mc/spigot/world_the_end
      - velocity_data:/mc/velocity
      - server_images:/mc/server/images
    ports:
      - "25565:25565"  # Spigot server port
      - "25577:25577"  # Velocity proxy port
    stdin_open: true
    tty: true

volumes:
  minecraft_data:
  minecraft_data_nether:
  minecraft_data_the_end:
  velocity_data:
  server_images:
