# FMC Configuration File
Portals:
    Move: false
    Wand: false
    Menu: false

MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""

Socket:
    Server_Port: 

Discord:
    Webhook_URL: ""

MCVC:
    Mode: false
    Host: "localhost"
    EXE_Path: ""

AutoStop:
    Mode: false
    Interval: 3