# FMC Configuration File
MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""
  
Socket:
    Client_Port: 
    Server_Port: 
    Buffered_Server_Port: 

Discord:
    Webhook_URL: ""
    Emoji_Add_Path: ""
    InvaderComingImageUrl: ""
    MaintenanceOnImageUrl: ""
    MaintenanceOffImageUrl: ""

Interval:
    Login: 
    Session: 3
    Request: 
    Start_Server: 

Debug:
    Mode: false
    ChannelId: ""
    Webhook_URL: ""
    Test: 

Permission:
    Detail_Name:
        - something.permission
    Short_Name:
        - someperm

Conv:
    Mode: false
    Host: "localhost"
    EXE_Path: ""