# FMC Configuration File
MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""
  
Socket:
    Client_Port: 
    Server_Port: 
    Buffered_Server_Port: 

Discord:
    Token: ""
    GuildId: 
    ChannelId: 
    Webhook_URL: ""
    InviteUrl: ""
    InvaderComingImageUrl: ""
    MaintenanceOnImageUrl: ""
    MaintenanceOffImageUrl: ""
    FirstJoinEmojiName: ""
    AddMemberEmojiName: ""
    JoinEmojiName: ""
    MoveEmojiName: ""
    ExitEmojiName: ""
    StartEmojiName: ""
    RequestEmojiName: ""
    RequestOKName: ""
    RequestCancelName: ""
    RequestNoResName: ""

Interval:
    Login: 
    Session: 3
    Request: 
    Start_Server: 

Debug:
    Mode: false
    ChannelId: ""
    Webhook_URL: ""
    Test: 

Permission:
    Detail_Name:
        - something.permission
    Short_Name:
        - someperm

Conv:
    Mode: false
    Host: "localhost"
    EXE_Path: ""