# Configuration File for Velocity Plugin (AWS Discord Bot Integration)
EventMessage:
  Join: ""

MySQL:
  Host: ""
  Database: ""
  Port: 3306
  User: ""
  Password: ""

Socket:
  Server_Port: 6000

# AWS Discord Service Configuration
AWS:
  Region: "ap-northeast-1"
  ApiGateway:
    Endpoint: "YOUR_AWS_API_GATEWAY_ENDPOINT"
    AccessKey: "YOUR_AWS_ACCESS_KEY"
    SecretKey: "YOUR_AWS_SECRET_KEY"

Debug:
  Mode: false
  Test: false

Permission:
  Detail_Name:
    - something.permission
  Short_Name:
    - someperm

Conv:
  Mode: false
  Host: "localhost"
  EXE_Path: ""

MaxMemory: 0
