# Configuration File for Velocity Plugin (AWS Discord Bot Integration)
EventMessage:
  Join: ""

MySQL:
  Host: ""
  Database: ""
  Port: 3306
  User: ""
  Password: ""

Socket:
  Server_Port: 6000

# AWS SQS Communication Configuration (New naming)
AWS:
  Region: "ap-northeast-1"
  SQS:
    ToMcQueueUrl: "YOUR_TO_MC_QUEUE_URL"
    ToWebQueueUrl: "YOUR_TO_WEB_QUEUE_URL"
    ToDiscordQueueUrl: "YOUR_TO_DISCORD_QUEUE_URL"
    Credentials:
      AccessKey: "YOUR_MC_WEB_SQS_ACCESS_KEY"
      SecretKey: "YOUR_MC_WEB_SQS_SECRET_KEY"

# Redis Configuration for kishax-api integration
Redis:
  URL: "redis://localhost:6379"

# MC Auth API Configuration
Auth:
  API:
    URL: "http://localhost:8080"
    KEY: "local-dev-api-key"

Debug:
  Mode: false
  Test: false

Permission:
  Detail_Name:
    - something.permission
  Short_Name:
    - someperm

Translate:
  romaji: false

# Settings that will be synced to MySQL settings table
Settings:
  MAX_IMAGE_TILES: 100
  LARGE_IMAGE_LIMIT_TIMES: 5
  IMAGE_LIMIT_TIMES: 10
  IMAGE_FOLDER: "/mc/server/images"
  CONFIRM_URL: "https://your-confirm-url.com"
  HOME_SERVER_NAME: "main"
  HOME_SERVER_IP: "127.0.0.1"
  INPUT_PERIOD: 60
  HUB_TELEPORT_TIME: 3

MaxMemory: 0
