modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="${projectIssueTracker}"
[[mods]]
modId="kishax"
version="${projectVersion}"
displayName="${projectName}"
displayURL="${projectHP}"
logoFile="logo.png"
authors="Takaya Maekawa"
description="${projectDescription}"
[[dependencies.kishax]]
modId="luckperms"
mandatory=false
versionRange="[5.4,)"
ordering="NONE"
side="SERVER"
