name: FMC-Plugin
version: 0.0.1
main: common.Main
author: Bella
website: keypforev.ddns.net
api-version: 1.16
description: "§6§lThis plugin is provided by FMC Server!!"
depends: [LunaChat]
commands:
  fmcp:
    usage: /<command>
    description: You can use FMC Bungeecord server command!
    executor: bungee_command.FMCCommand
  fmc:
    usage: /<command>
    description: You can use FMC Spigot server command!
    executor: spigot_command.FMCCommand
  hub:
    usage: /<command>
    description: You can back to Hub server!
    executor: bungee_command.Hub